### ISSUE TITLE
fs.exists uses true/false node-style callback which breaks monoclize

### ISSUE THREAD

**Issue by benjie** [jlipps/monocle-fs#1]
Node.js callbacks have two forms: `(err, result) => {...}` (as in `fs.writeFile`) and `bool => {...}` (as in `fs.exists`); monoclize only seems to work with the former and hence if you do `yield monoclefs.exists(filename)` and it does exist it will see the result `true` which it thinks is an error, and thus it will throw it rather than returning it.

**Comment by jlipps** [comment]
That is correct. I didn't want to get too fancy with the kinds of functions monoclize would work on and chose to stick with the more universal convention. `fs.exists` is now deprecated in any case. If you want to submit a PR that does some kind of check on the first callback arg to see if it is actually an error, I'd certainly consider merging it though.

**Comment by benjie** [comment]
So it is! Well since it's stability 0 (presumably because they're making everything follow the `(err, result) => {...}` model?) I'll just close this issue. Thanks!

**Comment by jlipps** [comment]
Yeah makes sense to me. Thanks for your interest.
